# Example configuration
command:
  # Name of the Command.
  saySomething:
    # Does the Player need to sneak to execute the command?
    # True/False
    requireShift: True
    # Which permission is required to execute this command?
    permission: f-command.example
    # Which command should be executed as the player?
    # Enter without /
    command: say hey
    # should the event be canceled?
    cancel: true



