# Only turn this on if you're asked by the Dev
# Might spam your console and/or chat ;-)
debug: false

# Example configuration
command:
  # Name of the Command.
  command1:
    key: f  # f or q
    # Does the Player need to sneak to execute the command?
    # True/False
    requireShift: false
    # Which permission is required to execute this command?
    permission: f-command.example
    # Which command should be executed as the player?
    # You can also use PlaceholderAPI here!
    # Enter without /
    command: say f no shift
    # should the original action be canceled?
    cancel: true
    # Should the command be executed from the Server?
    executeAsServer: false
    item: STONE

  command2:
    key: F
    requireShift: True
    permission: f-command.example
    command: say F shift
    cancel: true
    executeAsServer: false

  command3:
    key: q
    requireShift: True
    permission: f-command.example
    command: say q shift
    cancel: true
    executeAsServer: false

  command4:
    key: Q
    requireShift: false
    permission: f-command.example
    command: say Q no shift
    cancel: true
    executeAsServer: false


