# Only turn this on if your asked by the Dev
# Might spam your console and/or chat ;-)
debug: false

# Example configuration
command:
  # Name of the Command.
  command1:
    key: f  # f or q
    # Does the Player need to sneak to execute the command?
    # True/False
    requireShift: false
    # Which permission is required to execute this command?
    permission: f-command.example
    # Which command should be executed as the player?
    # You can also use PlaceholderAPI here!
    # Enter without /
    command: say hey try the F key again while pressing shift
    # should the event be canceled?
    cancel: true
    # Should the command be executed from the Server?
    executeAsServer: false
    item: STONE

  command2:
    key: f  # f or q
    # Does the Player need to sneak to execute the command?
    # True/False
    requireShift: True
    # Which permission is required to execute this command?
    permission: f-command.example
    # Which command should be executed as the player?
    # You can also use PlaceholderAPI here!
    # Enter without /
    command: say Cool, you did it!
    # should the event be canceled?
    cancel: true
    # Should the command be executed from the Server?
    executeAsServer: false


