# Only turn this on if you're asked to
# Might spam your console and/or chat ;-)
debug: false

# Example configuration
command:
  # Name of the Command.
  command1:
    # Key to press (f or q)
    key: f
    # Does the Player need to sneak to execute the command?
    # True/False
    requireShift: false  # Default true
    # Which permission is required to execute this command?
    permission: f-command.example  # Default none
    # Which command should be executed?
    # You can also use PlaceholderAPI here!
    # Enter without /
    command: say f no shift
    # Stopping item drop or hand swap from happening
    cancel: true  # Default false
    # Should the command be executed from the Server?
    executeAsServer: false  # default false

  command2:
    key: F
    requireShift: True
    permission: f-command.example
    command: say F shift
    cancel: true
    executeAsServer: false

  command3:
    key: q
    requireShift: True
    permission: f-command.example
    command: say q shift
    cancel: true
    executeAsServer: false

  command4:
    key: Q
    requireShift: false
    permission: f-command.example
    command: say Q no shift
    cancel: true
    executeAsServer: false


