name: F-Command
version: '${project.version}'
main: ch.hutch79.Main
api-version: 1.19
authors: [ Hutch79 ]
description: F-Command executes a command if the Player switches his/here offhand
website: https://hutch79.ch/
