name: F-Command
version: '${project.version}'
main: ch.hutch79.Application.FCommand
api-version: 1.13
authors: [ Hutch79 ]
description: F-Command executes a command if the Player switches his/here offhand
website: https://hutch79.ch/
commands:
  fcommand:
    aliases: fcmd
    permission: fcommand.admin
softdepend:
  - PlaceholderAPI
